apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-istio-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/PacktPublishing/ArgoCD-in-Practice.git
    targetRevision: feat/ch06
    path: ch05/applications/argocd-ui

  destination:
    namespace: argocd-ui
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
