apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/PacktPublishing/ArgoCD-in-Practice.git
    targetRevision: HEAD
    path: ch05/applications/istio-control-plane

  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
