apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/istio/istio.git
    targetRevision: "1.12.0"
    path: manifests/charts/istio-operator
    helm:
      parameters:
        - name: "hub"
          value: "docker.io/istio"
        - name: "tag"
          value: "1.12.0"

  destination:
    namespace: istio-operator
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
