apiVersion: batch/v1
kind: Job
metadata:
  generateName: integration-tests
  namespace: team-demo
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: run-tests
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args:
          - if [ $(curl -s -o /dev/null -w '%{http_code}'  rollout-bluegreen-preview/version) != "200" ]; then exit 22; fi;
            if [[ "$(curl -s rollout-bluegreen-preview/version)" != "APP_VERSION" ]]; then exit 22; fi;
            echo "Tests completed successfully"
      restartPolicy: Never
  backoffLimit: 2
