kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-role
  namespace: team-demo
rules:
  - apiGroups: ["argoproj.io"]
    resources: 
      - "rollouts"
      - "rollouts/status"
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-role-binding
  namespace: team-demo
subjects:
- kind: ServiceAccount
  name: default
  namespace: team-demo
roleRef:
  kind: Role
  name: test-role
  apiGroup: rbac.authorization.k8s.io
