apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ch06-blue-green
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app:  app
    version: "1.0"
